nitter:
  service: nitter
  rss-url: https://uk.unofficialbird.com/{{ custom }}/rss
  descriptor: ğŸ¦ Tweet

proxitok:
  service: proxitok
  rss-url: https://proxitok.pabloferreiro.es/@{{ custom }}/rss
  descriptor: ğŸ¶ TikTok

invidious:
  service: invidious
  rss-url: https://invidious.snopyta.org/feed/channel/{{ custom }}
  descriptor: ğŸ“½ YouTube video

teddit:
  service: teddit
  rss-url: https://teddit.net/r/{{ custom }}?api&type=rss
  descriptor: ğŸ© Reddit post

